# Generated by Django 3.0.5 on 2020-05-13 06:47

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.FileField(null=True, upload_to=Main.models.upload_path),
        ),
        migrations.AddField(
            model_name='course',
            name='ratings',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='Linkdein',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Education',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Institute_Organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Linkdein',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Specialization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
