# Generated by Django 3.0.5 on 2020-05-13 08:06

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200513_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignment',
            field=models.FileField(blank=True, null=True, upload_to=Main.models.upload_path),
        ),
    ]
