# Generated by Django 3.0.5 on 2020-05-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200514_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skype_link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skype_link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
