# Generated by Django 3.0.5 on 2020-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200514_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skype_link',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skype_link',
        ),
        migrations.AddField(
            model_name='student',
            name='skype_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skype_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
