# Generated by Django 3.0.5 on 2020-05-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20200519_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulefile',
            name='modulefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulefile', to='Main.Module'),
        ),
    ]
