# Generated by Django 3.0.5 on 2020-05-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20200519_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulefile',
            old_name='modulefile',
            new_name='module',
        ),
    ]
