# Generated by Django 3.0.6 on 2020-05-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20200527_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='student',
            new_name='user',
        ),
    ]
