# Generated by Django 3.0.6 on 2020-06-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20200528_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefile',
            old_name='coursefile',
            new_name='course',
        ),
    ]
